apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-policy-component
  labels:
    app: api-policy-component
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-policy-component
  template:
    metadata:
      labels:
        app: api-policy-component
        visualize: "true"
    spec:
      containers:
      - name: api-policy-component
        image: coco/api-policy-component:k8s_v0.0.5
        env:
        - name: JAVA_OPTS
          value: "-Xms384m -Xmx384m -XX:+UseG1GC -server"
        - name: GRAPHITE_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.host
        - name: GRAPHITE_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.port
        - name: READ_ENDPOINT
          value: "path-routing-varnish:80"
        - name: JERSEY_TIMEOUT_DURATION
          value: "10000ms"
        - name: GRAPHITE_PREFIX
          value: "coco.services.k8s.api-policy-component"
        ports:
        - containerPort: 8080
        - containerPort: 8081
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: api-policy-component
  labels:
    app: api-policy-component
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "app"
      targetPort: 8080
    - port: 8081
      name: "admin"
      targetPort: 8081
  selector:
    app: api-policy-component
