apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: brands-rw-neo4j-red
  labels:
    app: brands-rw-neo4j-red
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brands-rw-neo4j-red
  template:
    metadata:
      labels:
        app: brands-rw-neo4j-red
        visualize: "true"
    spec:
      containers:
      - name: brands-rw-neo4j-red
        image: coco/brands-rw-neo4j:v0.1.5
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
        env:
        - name: APP_PORT
          value: "8080"
        - name: GRAPHITE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: GRAPHITE_PREFIX
          value: "coco.services.k8s.brands-rw-neo4j-red"
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: neo4j.statements.batch.size	
        - name: NEO_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: neo4j.url  
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: brands-rw-neo4j-red
  labels:
    app: brands-rw-neo4j-red
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "app"
      targetPort: 8080
  selector:
    app: brands-rw-neo4j-red
