apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: brightcove-annotations-rw-red
  labels:
    app: brightcove-annotations-rw-red
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brightcove-annotations-rw-red
  template:
    metadata:
      labels:
        app: brightcove-annotations-rw-red
        visualize: "true"
    spec:
      containers:
      - name: brightcove-annotations-rw-red
        image: coco/annotations-rw-neo4j:v0.1.8
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        env:
        - name: PLATFORM_VERSION
          value: "brightcove"
        - name: NEO_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: neo4j.read.write.url  
        - name: BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: neo4j.statements.batch.size	
        - name: GRAPHITE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: GRAPHITE_PREFIX
          value: "coco.services.k8s.v1-annotations-rw-neo4j-red"
        - name: LOG_METRICS
          value: "false"
        - name: APP_PORT
          value: "8080"
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: brightcove-annotations-rw-red
  labels:
    app: brightcove-annotations-rw-red
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: brightcove-annotations-rw-red