apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cms-kafka-bridge-pub-pre-prod
  labels:
    app: cms-kafka-bridge-pub-pre-prod
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms-kafka-bridge-pub-pre-prod
  template:
    metadata:
      labels:
        app: cms-kafka-bridge-pub-pre-prod
        visualize: "true"
    spec:
      containers:
      - name: cms-kafka-bridge-pre-prod
        image:  coco/coco-kafka-bridge:remove-host-based-routing-rc2
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: certificates-storage
        env:
        - name: QUEUE_PROXY_ADDRS
          value: "https://pub-pre-prod-uk-up.ft.com/__kafka-rest-proxy"
        - name: GROUP_ID
          value: "k8s-kafka-bridge-pub-pre-prod-1"
        - name: CONSUMER_AUTOCOMMIT_ENABLE
          value: "true"
        - name: TOPIC
          value: "NativeCmsPublicationEvents"
        - name: PRODUCER_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: kafka.proxy.url
        - name: PRODUCER_HOST_HEADER
          value: "kafka-proxy"
        - name: PRODUCER_TYPE
          value: "proxy"
        - name: AUTHORIZATION_KEY
          valueFrom:
            secretKeyRef:
              name: pub-auth
              key: pub-pre-prod-auth
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - name: certificates-storage
        hostPath:
          path: /usr/share/ca-certificates

---

kind: Service
apiVersion: v1
metadata:
  name: cms-kafka-bridge-pub-pre-prod
  labels:
    app: cms-kafka-bridge-pub-pre-prod
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "cms-kafka-bridge-pub-pre-prod"
      targetPort: 8080
  selector:
    app: cms-kafka-bridge-pub-pre-prod

