apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: concept-ingester-red
  labels:
    app: concept-ingester-red
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: concept-ingester-red
  template:
    metadata:
      labels:
        app: concept-ingester-red
        visualize: "true"
    spec:
      containers:
      - name: concept-ingester-red
        image: coco/concept-ingester:remove-vulcan-based-routing
        imagePullPolicy: Always
        resources:
            limits:
              memory: 256Mi
        env:
        - name: PORT
          value: "8080"
        - name: KAFKA_PROXY_ADDRESS
          value: "http://kafka:8082"
        - name: GROUP_ID
          value: "RedConcepts"
        - name: TOPIC
          value: "Concept"
        - name: SERVICES
          value: "http://content-rw-neo4j-red:8080,http://people-rw-neo4j-red:8080,http://organisations-rw-neo4j-red:8080,http://memberships-rw-neo4j-red:8080,http://brands-rw-neo4j-red:8080,http://roles-rw-neo4j-red:8080,http://alphaville-series-rw-neo4j-red:8080,http://financial-instruments-rw-neo4j-red:8080,http://special-reports-rw-neo4j-red:8080,http://locations-rw-neo4j-red:8080,http://genres-rw-neo4j-red:8080,http://topics-rw-neo4j-red:8080,http://sections-rw-neo4j-red:8080,http://subjects-rw-neo4j-red:8080,http://industry-classifications-rw-neo4j-red:8080"
        - name: ELASTICSEARCH_WRITER_ADDRESS
          value: "http://concept-rw-elasticsearch:8080"
        - name: QUEUE_ID
          value: "kafka"
        - name: GRAPHITE_TCP_AUTHORITY
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: GRAPHITE_PREFIX
          value: "coco.services.k8s.concept-ingester-red"
        - name: OFFSET
          value: "largest"
        - name: COMMIT_ENABLE
          value: "true"
        - name: STREAM_COUNT
          value: "1"
        - name: TIMEOUT
          value: "60"
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        # The probe has been disabled because the concept-rw-elasticsearch gtg will return 503 because the elasticsearch cluster status is yellow. 
        # The elasticsearch cluster will be yellow as long as it's configured to use only one node.
        # The readiness probe can be enabled when using a proper cluster configuration.
        # readinessProbe:
        #   httpGet:
        #     path: /__gtg
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: concept-ingester-red
  labels:
    app: concept-ingester-red
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "8080"
      targetPort: 8080
  selector:
    app: concept-ingester-red
