apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: content-public-read
  labels:
    app: content-public-read
    visualize: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: content-public-read
  template:
    metadata:
      labels:
        app: content-public-read
        version: "latest"
        visualize: "true"
    spec:
      containers:
      - name: content-public-read
        image: up-registry.ft.com/coco/content-public-read
        env:
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx128m -XX:+UseG1GC -server"
        - name: VULCAN_HOST
          value: document-store-api.default.svc.cluster.local:8080:8081
        - name: "CONTENT_PATH"
          value: content/
        - name: "HOST_HEADER"
          value: document-store-api
        - name: "CONTENT_HEALTHCHECK_PATH"
          value: /__health
        - name: "API_HOST"
          value: test.api.ft.com
        ports:
        - containerPort: 8080
        - containerPort: 8081
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: content-public-read
  labels:
    app: content-public-read
    visualize: "true"
    hasHealthcheck: "true"
    healthcheckSeverity: warning
spec:
  ports:
    - port: 8080
      name: "8080"
      targetPort: 8080
    - port: 8081
      name: "8081"
      targetPort: 8081
  selector:
    app: content-public-read
