apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: document-store-api
  labels:
    app: document-store-api
    visualize: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: document-store-api
  template:
    metadata:
      labels:
        app: document-store-api
        visualize: "true"
    spec:
      containers:
      - name: document-store-api
        image: up-registry.ft.com/coco/document-store-api:v94
        env:
        - name: MONGO_ADDRESSES
          value: mongodb-0.mongodb.default.svc.cluster.local:27017,mongodb-1.mongodb.default.svc.cluster.local:27017,mongodb-2.mongodb.default.svc.cluster.local:27017
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx128m -XX:+UseG1GC -server"
        - name: CACHE_TTL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: cache-max-age
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: api.host
        ports:
        - containerPort: 8080
        - containerPort: 8081
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
---

kind: Service
apiVersion: v1
metadata:
  name: document-store-api
  labels:
    app: document-store-api
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "8080"
      targetPort: 8080
    - port: 8081
      name: "8081"
      targetPort: 8081
  selector:
    app: document-store-api
