apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: enriched-content-read-api
  labels:
    app: enriched-content-read-api
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enriched-content-read-api
  template:
    metadata:
      labels:
        app: enriched-content-read-api
        visualize: "true"
    spec:
      containers:
      - name: enriched-content-read-api
        image: up-registry.ft.com/coco/enriched-content-read-api:k8s_v2
        env:
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx128m -XX:+UseG1GC -server"
        - name: CONTENT_API_HOST
          value: content-public-read:8080
        - name: ANNOTATIONS_API_HOST
          value: public-annotations-api:8080
        - name: CACHE_TTL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: cache-max-age
        ports:
        - containerPort: 8080
        - containerPort: 8081
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet: 
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
---

kind: Service
apiVersion: v1
metadata:
  name: enriched-content-read-api
  labels:
    app: enriched-content-read-api
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "app"
      targetPort: 8080
    - port: 8081
      name: "admin"
      targetPort: 8081
  selector:
    app: enriched-content-read-api
