apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: genres-rw-neo4j-red
  labels:
    app: genres-rw-neo4j-red
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: genres-rw-neo4j-red
  template:
    metadata:
      labels:
        app: genres-rw-neo4j-red
        visualize: "true"
    spec:
      containers:
      - name: genres-rw-neo4j-red
        image: coco/genres-rw-neo4j:v1.1.6
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
        env:
        - name: GRAPHITE_ADDRESS
          value: "graphite.ft.com:2003"
        - name: GRAPHITE_PREFIX
          value: "coco.services.k8s.genres-rw-neo4j-red"
        - name: BATCH_SIZE
          value: "50"
        - name: NEO_URL
          value: "http://neo4j-red:7474/db/data/" 
        ports:
        - containerPort:  8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: genres-rw-neo4j-red
  labels:
    app: genres-rw-neo4j-red
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "app"
      targetPort: 8080
  selector:
    app: genres-rw-neo4j-red
