apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: internal-content-api
  labels:
    app: internal-content-api
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: internal-content-api
  template:
    metadata:
      labels:
        app: internal-content-api
        visualize: "true"
    spec:
      containers:
      - name: internal-content-api
        image: coco/internal-content-api:gtg-fix
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
        env:
        - name: APP_PORT
          value: "8080"
        - name: APP_NAME
          value: internal-content-api
        - name: CONTENT_SOURCE_URI
          value: http://enriched-content-read-api:8080/enrichedcontent
        - name: INTERNAL_COMPONENTS_SOURCE_URI
          value: http://document-store-api:8080/internalcomponents
        - name: CONTENT_SOURCE_APP_HEALTH_URI
          value: http://enriched-content-read-api:8080/__health
        - name: INTERNAL_COMPONENTS_SOURCE_APP_HEALTH_URI
          value: http://document-store-api:8080/__health
        - name: CONTENT_SOURCE_APP_NAME
          value: enriched-content-read-api
        - name: INTERNAL_COMPONENTS_SOURCE_APP_NAME
          value: document-store-api
        - name: CONTENT_SOURCE_APP_PANIC_GUIDE
          value: https://dewey.ft.com/enriched-content-read-api.html
        - name: INTERNAL_COMPONENTS_SOURCE_APP_PANIC_GUIDE
          value: https://dewey.ft.com/document-store-api.html
        - name: CONTENT_SOURCE_APP_BUSINESS_IMPACT
          value: "No articles would be available"
        - name: INTERNAL_COMPONENTS_SOURCE_APP_BUSINESS_IMPACT
          value: "Articles won't have the internal components"
        - name: ENV_API_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: api.host
        - name: CACHE_CONTROL_POLICY
        #TODO build dynamically somehow?
          value: "max-age=10"
        - name: GRAPHITE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: GRAPHITE_PREFIX
          value: "coco.services.k8s.internal-content-api"
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: internal-content-api
  labels:
    app: internal-content-api
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: internal-content-api
