apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  methode-list-mapper
  labels:
    app:  methode-list-mapper
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: methode-list-mapper
  template:
    metadata:
      labels:
        app:  methode-list-mapper
        visualize: "true"
    spec:
      containers:
      - name:  methode-list-mapper
        image:  up-registry.ft.com/coco/methode-list-mapper:v10
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
        livenessProbe:
          initialDelaySeconds: 15
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        env:
        - name: DOCUMENT_STORE_API_URL
          value: "document-store-api:8080" 
        - name: CONCORDANCE_API_URL
          value: "public-concordances-api:8080"
        - name: THINGS_API_URL
          value: "public-things-api:8080"
        - name: KAFKA_PROXY_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: kafka.proxy.url
        ports:
        - containerPort: 8080
        - containerPort: 8081

---

kind: Service
apiVersion: v1
metadata:
  name: methode-list-mapper
  labels:
    app: methode-list-mapper
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "app"
      targetPort: 8080
    - port: 8081
      name: "admin"
      targetPort: 8081
  selector:
    app: methode-list-mapper
