apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: methode-image-model-mapper
  labels:
    app: methode-image-model-mapper
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: methode-image-model-mapper
  template:
    metadata:
      labels:
        app: methode-image-model-mapper
        visualize: "true"
    spec:
      containers:
      - name: methode-image-model-mapper
        image: coco/methode-image-model-mapper:v16.0.2-rc.1
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx256m -XX:+UseG1GC -server"
        - name: KAFKA_PROXY
          value: "kafka:8082"
        - name: S3_URL
          value: "http://com.ft.coco-imagepublish.pre-prod.s3.amazonaws.com/"
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: methode-image-model-mapper
  labels:
    app: methode-image-model-mapper
    visualize: "true"
    hasHealthcheck: "true"
    healthcheckSeverity: warning
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: methode-image-model-mapper
