apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: methode-article-internal-components-mapper
  labels:
    app: methode-article-internal-components-mapper
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: methode-article-internal-components-mapper
  template:
    metadata:
      labels:
        app: methode-article-internal-components-mapper
        visualize: "true"
    spec:
      containers:
      - name: methode-article-internal-components-mapper
        image: coco/methode-article-internal-components-mapper:remove-host-routing-1
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        env:
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx128m -XX:+UseG1GC -server" 
        - name: METHODE_ARTICLE_MAPPER_URL
          value: "methode-article-mapper:8080" 
        - name: KAFKA_PROXY_URL
          value: "kafka:8082"
        ports:
        - containerPort: 8080
        - containerPort: 8081

---

kind: Service
apiVersion: v1
metadata:
  name: methode-article-internal-components-mapper
  labels:
    app: methode-article-internal-components-mapper
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "app"
      targetPort: 8080
    - port: 8081
      name: "admin"
      targetPort: 8081
  selector:
    app: methode-article-internal-components-mapper
