###############################################################################
# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb1
  labels:
    app: mongodb1
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb1
  template:
    metadata:
      labels:
        app: mongodb1
        version: "latest"
        visualize: "true"
    spec:
      containers:
      - name: mongodb1
        image: coco/mongodb
        resources:
          limits:
            memory: 4000Mi
#            cpu: 1.1
        ports:
        - containerPort: 27017
        - containerPort: 28017
        volumeMounts:
         - name: mongo-persistent-storage-a
           mountPath: /data/db
      volumes:
       - name: mongo-persistent-storage-a
         awsElasticBlockStore:
           volumeID: vol-0bb86d36163a5d389
           fsType: ext4
---

kind: Service
apiVersion: v1
metadata:
  name: mongodb1
  labels:
    app: mongodb1
    visualize: "true"
spec:
  ports:
    - name: work
      port: 27017
      targetPort: 27017
    - name: admin
      port: 28017
      targetPort: 28017
  selector:
    app: mongodb1
