apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nativerw
  labels:
    app: nativerw
    visualize: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nativerw
  template:
    metadata:
      labels:
        app: nativerw
        version: "latest"
        visualize: "true"
    spec:
      containers:
      - name: nativerw
        image: coco/nativerw
        env:
        - name: MONGOS
          value: mongodb:27017
        resources:
          limits:
            memory: 256Mi
#            cpu: 1.1
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: nativerw
  labels:
    app: nativerw
    visualize: "true"
    hasHealthcheck: "true"
    healthcheckSeverity: warning
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: nativerw
