apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: path-routing-varnish
  labels:
    app: path-routing-varnish
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: path-routing-varnish
  template:
    metadata:
      labels:
        app: path-routing-varnish
        version: "latest"
        visualize: "true"
    spec:
      containers:
      - name: path-routing-varnish
        image: coco/delivery-varnish:routing-test
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: path-routing-varnish
  labels:
    app: path-routing-varnish
    visualize: "true"
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: path-routing-varnish
