apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  public-concordances-api
  labels:
    app:  public-concordances-api
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: public-concordances-api
  template:
    metadata:
      labels:
        app:  public-concordances-api
        visualize: "true"
    spec:
      containers:
      - name:  public-concordances-api
        image:  coco/public-concordances-api:v0.1.6
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
        env:
        - name: APP_PORT
          value: "8080" 
        - name: GRAPHITE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: GRAPHITE_PREFIX
          value: "coco.services.k8s.public-concordances-api"
        - name: LOG_METRICS
          value: "false" 
        - name: CACHE_DURATION
          value: "10m" 
        - name: NEO_URL
          value: "http://neo4j-red:7474/db/data/" 
        ports:
        - containerPort:  8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: public-concordances-api
  labels:
    app: public-concordances-api
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "8080"
      targetPort: 8080
  selector:
    app: public-concordances-api