apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: relations-api
  labels:
    app: relations-api
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: relations-api
  template:
    metadata:
      labels:
        app: relations-api
        visualize: "true"
    spec:
      containers:
      - name: relations-api
        image: coco/relations-api:v1.0.1
        resources:
          limits:
            memory: 256Mi
        env:
        - name: APP_PORT
          value: "8080"
        - name: NEO_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: neo4j.url
        - name: GRAPHITE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: GRAPHITE_PREFIX
          value: "coco.services.k8s.relations-api"
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: relations-api
  labels:
    app: relations-api
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: relations-api
