apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: synthetic-image-publication-monitor
  labels:
    app: synthetic-image-publication-monitor
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synthetic-image-publication-monitor
  template:
    metadata:
      labels:
        app: synthetic-image-publication-monitor
        visualize: "true"
    spec:
      containers:
      - name: synthetic-image-publication-monitor
        image:  coco/coco-synthetic-image-publication-monitor:kubernetes-version-rc2
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
        env:
        - name: POST_ADDRESS
          value: "cms-notifier:8080"
        - name: BUCKET_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: aws.s3.image.binaries.bucket
        - name: TEST_UUID
          value: "6a70679a-fd9b-4d64-9bec-2d340fb75021"
        ports:
        - containerPort:  8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
# At this time, gtg endpoint is not implemented. Enable the readinessProbe when this endpoint will be available.
#        readinessProbe:
#          httpGet:
#            path: "/__gtg"
#            port: 8080
#          initialDelaySeconds: 15
#          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: synthetic-image-publication-monitor
  labels:
    app: synthetic-image-publication-monitor
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "app"
      targetPort: 8080
  selector:
    app: synthetic-image-publication-monitor
