apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: topics-rw-neo4j
  labels:
    app: topics-rw-neo4j
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: topics-rw-neo4j
  template:
    metadata:
      labels:
        app: topics-rw-neo4j
        visualize: "true"
    spec:
      containers:
      - name: topics-rw-neo4j
        image: coco/topics-rw-neo4j:v1.1.3
        env:
        - name: NEO_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: neo4j.read.write.url  
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: topics-rw-neo4j
  labels:
    app: topics-rw-neo4j
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: topics-rw-neo4j
