apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: topics-rw-neo4j-red
  labels:
    app: topics-rw-neo4j-red
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topics-rw-neo4j-red
  template:
    metadata:
      labels:
        app: topics-rw-neo4j-red
        version: "latest"
        visualize: "true"
    spec:
      containers:
      - name: topics-rw-neo4j-red
        image: coco/topics-rw-neo4j:v1.1.3
        env:
          - name: NEO_URL
            value: http://neo4j-red:7474/db/data/
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: topics-rw-neo4j-red
  labels:
    app: topics-rw-neo4j-red
    visualize: "true"
    hasHealthcheck: "true"
    healthcheckSeverity: warning
spec:
  ports:
    - name: work
      port: 8080
      targetPort: 8080
  selector:
    app: topics-rw-neo4j-red
