apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-image-mapper
  labels:
    app: wordpress-image-mapper
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-image-mapper
  template:
    metadata:
      labels:
        app: wordpress-image-mapper
        visualize: "true"
    spec:
      containers:
      - name: wordpress-image-mapper
        image: up-registry.ft.com/coco/wordpress-image-mapper:v35
        env:
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx256m -XX:+UseG1GC -server"
        - name: KAFKA_PROXY
          value: "kafka:8082"
        ports:
        - containerPort: 8080
        - containerPort: 8081
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: wordpress-image-mapper
  labels:
    app: wordpress-image-mapper
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "8080"
      targetPort: 8080
    - port: 8081
      name: "8081"
      targetPort: 8081
  selector:
    app: wordpress-image-mapper
