apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: mongo-configurator
  labels:
    app: mongo-configurator
    visualize: "true"
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: "Replace"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
          - name: mongo-configurator
            image: coco/coco-mongodb-configurator
            env:
            - name: ARGS
              value: "mongodb-0.mongodb:27017:28017 mongodb-1.mongodb:27017:28017 mongodb-2.mongodb:27017:28017"
