apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: burrow
  labels:
    app: burrow
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burrow
  template:
    metadata:
      labels:
        app: burrow
        visualize: "true"
    spec:
      containers:
      - name: burrow
        image:  coco/burrow:v1.0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
        env:
        - name: ZOOKEEPER_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: zookeeper.host
        - name: ZOOKEEPER_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: zookeeper.port
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: kafka.host
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: kafka.port
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: burrow
  labels:
    app: burrow
    visualize: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: burrow

