apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: concepts-kafka-bridge-pub-k8s
  labels:
    app: concepts-kafka-bridge-pub-k8s
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concepts-kafka-bridge-pub-k8s
  template:
    metadata:
      labels:
        app: concepts-kafka-bridge-pub-k8s
        visualize: "true"
    spec:
      containers:
      - name: concepts-kafka-bridge-k8s
        image:  coco/coco-kafka-bridge:14.2.0-k8s-removed-host-based-routing-rc.2
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: certificates-storage
        env:
        - name: QUEUE_PROXY_ADDRS
          value: "https://k8s-publishing-upp-eu.ft.com/__kafka-rest-proxy"
        - name: GROUP_ID
          value: "concepts-kafka-bridge-pub-k8s"
        - name: CONSUMER_AUTOCOMMIT_ENABLE
          value: "true"
        - name: TOPIC
          value: "Concept"
        - name: PRODUCER_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: kafka.proxy.url.with.protocol
        - name: PRODUCER_TYPE
          value: "proxy"
        - name: AUTHORIZATION_KEY
          valueFrom:
            secretKeyRef:
              name: pub-auth
              key: pub-k8s-auth
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - name: certificates-storage
        hostPath:
          path: /usr/share/ca-certificates

---

kind: Service
apiVersion: v1
metadata:
  name: concepts-kafka-bridge-pub-k8s
  labels:
    app: concepts-kafka-bridge-pub-k8s
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: concepts-kafka-bridge-pub-k8s

