apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: internal-components-preview
  labels:
    app: internal-components-preview
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: internal-components-preview
  template:
    metadata:
      labels:
        app: internal-components-preview
        visualize: "true"
    spec:
      containers:
      - name: internal-components-preview
        image: coco/content-preview:k8s_v0.0.3
        resources:
          limits:
            memory: 256Mi
        env:
        - name: APP_PORT
          value: "8080"
        - name: APP_NAME
          value: internal-components-preview
        - name: BUSINESS_IMPACT
          value: "Editorial users won't be able to preview internal components on articles"
        - name: TRANSFORM_APP_URI
          value: http://methode-article-internal-components-mapper:8080/map
        - name: TRANSFORM_APP_HEALTH_URI
          value: http://methode-article-internal-components-mapper:8080/__health
        - name: TRANSFORM_APP_NAME
          value: methode-article-internal-components-mapper
        - name: TRANSFORM_APP_PANIC_GUIDE
          value: https://dewey.ft.com/up-maicm.html
        - name: GRAPHITE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: GRAPHITE_PREFIX
          value: coco.services.k8s.internal-components-preview
        - name: SOURCE_APP_NAME
          value: methode-api
        - name: SOURCE_APP_URI
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: methode.api_uri
        - name: SOURCE_APP_HEALTH_URI
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: methode.health_uri
        - name: SOURCE_APP_AUTH
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: methode.authorization_key
        - name: SOURCE_APP_PANIC_GUIDE
          value: https://dewey.ft.com/up-mapi.html

        ports:
        - containerPort: 8080
        - containerPort: 8081
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
---

kind: Service
apiVersion: v1
metadata:
  name: internal-components-preview
  labels:
    app: internal-components-preview
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "app"
      targetPort: 8080
    - port: 8081
      name: "admin"
      targetPort: 8081
  selector:
    app: internal-components-preview
