apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: methode-image-binary-mapper
  labels:
    app: methode-image-binary-mapper
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: methode-image-binary-mapper
  template:
    metadata:
      labels:
        app: methode-image-binary-mapper
        visualize: "true"
    spec:
      containers:
      - name: methode-image-binary-mapper
        image: coco/methode-image-binary-mapper:v1.0.2
        env:
        - name: JAVA_OPTS
          value: "-Xms296m -Xmx296m -XX:+UseG1GC -server"
        - name: KAFKA_PROXY
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: kafka.proxy.url
        ports:
        - containerPort: 8080
        - containerPort: 8081
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: methode-image-binary-mapper
  labels:
    app: methode-image-binary-mapper
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "app"
      targetPort: 8080
    - port: 8081
      name: "admin"
      targetPort: 8081
  selector:
    app: methode-image-binary-mapper
