apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notifications-rw
  labels:
    app: notifications-rw
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications-rw
  template:
    metadata:
      labels:
        app: notifications-rw
        visualize: "true"
    spec:
      containers:
      - name: notifications-rw
        image: up-registry.ft.com/coco/notifications-rw:vgtg_endpoint
        env:
        - name: MONGO_ADDRESSES
          value: "mongodb-0.mongodb.default.svc.cluster.local:27017,mongodb-1.mongodb.default.svc.cluster.local:27017,mongodb-2.mongodb.default.svc.cluster.local:27017"
        - name: JAVA_OPTS
          value: "-Xms64m -Xmx64m -XX:+UseG1GC -server"
        - name: ARCHIVE_START_DATE
          value: "2006-02-09T02:00:42.999Z"
        - name: NODE_ID
          value: "b5aef703"
        - name: MAX_NODE_SKEW
          value: "120seconds"
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: api.host
        - name: CACHE_TTL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: cache-max-age
        ports:
        - containerPort: 8080
        - containerPort: 8081
        livenessProbe:
          initialDelaySeconds: 20
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: notifications-rw
  labels:
    app: notifications-rw
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "app"
      targetPort: 8080
    - port: 8081
      name: "admin"
      targetPort: 8081
  selector:
    app: notifications-rw
