apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: upp-aggregate-healthcheck
  labels:
    app: upp-aggregate-healthcheck
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upp-aggregate-healthcheck
  template:
    metadata:
      labels:
        app: upp-aggregate-healthcheck
        version: "latest"
        visualize: "true"
    spec:
      containers:
      - name: aggregate-healthcheck
        image: coco/upp-aggregate-healthcheck:v1.1.1-rc5
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
        env:
        - name: PATH_PREFIX
          value: "/__health"
        - name: GRAPHITE_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
---

kind: Service
apiVersion: v1
metadata:
  name: upp-aggregate-healthcheck
  labels:
    app: upp-aggregate-healthcheck
    visualize: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: upp-aggregate-healthcheck

---

kind: ConfigMapList
apiVersion: v1
items:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.default
      labels: 
         healthcheck-categories-for: aggregate-healthcheck
    data:
      category.name: default
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.publish
      labels: 
        healthcheck-categories-for: aggregate-healthcheck
    data:
      category.name: publish
      category.services: content-ingester, topics-rw
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.content-read
      labels: 
         healthcheck-categories-for: aggregate-healthcheck
    data:
      category.name: content-read
      category.services: api-policy-component,content-public-read,document-store-api
      category.refreshrate: "60"
      category.issticky: "false"
      category.enabled: "true"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.image-publish
      labels: 
         healthcheck-categories-for: aggregate-healthcheck
    data:
      category.name: image-publish
      category.services: content-ingester,binary-writer
      category.refreshrate: "60"
      category.issticky: "false"
      category.enabled: "true"

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: healthcheck.ack.messages
  labels: 
    healthcheck-acknowledgements-for: aggregate-healthcheck
data:
