debug_key_name: pac-provisioner-eu

# Controller Instance Properties
controller_instance_type: c5.large
controller_count: 2

# ETCD Instance Properties
etcd_instance_type: t3.medium
etcd_count: 3

# Worker Instance Properties
worker_pools:
  - {id: 1, instance_type: m5.large, count: 2, role: worker, subnets: 2} # using only 2 subnets to have nodes only in AZ a and b
  - {id: t, instance_type: r5.large, count: 1, rootVolumeSize: 110, role: thanos-worker, dedicatedtaint: thanos, subnets: 1} # using only 1 subnet to have nodes only in AZ a

worker_security_groups:
  - sg-17f58d6e
  - sg-9e99c1e6


tags:
  - {name: ipCode, value: P196}
  - {name: teamDL, value: universal.publishing.platform@ft.com}
  - {name: stopSchedule, value: nostop}
