debug_key_name: pac-provisioner-d-eu

# Controller Instance Properties
controller_instance_type: c5.large
controller_count: 2

# ETCD Instance Properties
etcd_instance_type: t3.medium
etcd_count: 3

# Worker Instance Properties
worker_pools: 
  - {id: 1, instance_type: m5.large, count: 2, role: worker, subnets: 2} # using only 2 subnets to have nodes only in AZ a and b

worker_security_groups:
  - sg-9a7630e2
  - sg-b186fec8


tags:
  - {name: ipCode, value: P196}
  - {name: teamDL, value: universal.publishing.platform@ft.com}
  - {name: stopSchedule, value: nostop}
