debug_key_name: upp-k8s-provisioning-debug

# Controller Instance Properties
controller_instance_type: c5.large
controller_count: 2

# ETCD Instance Properties
etcd_instance_type: t3.medium
etcd_count: 3

# Worker Instance Properties
worker_pools: 
  - {id: 1, instance_type: m5.xlarge, count: 3, role: worker, subnets: 2} # using only 2 subnets to have nodes only in AZ a and b
  - {id: 2, instance_type: m5.large, count: 3, role: mongo-worker, subnets: 3, dedicatedtaint: mongo}
  - {id: 3, instance_type: m5a.large, count: 1, role: kafka-worker, subnets: 1, dedicatedtaint: kafka}

worker_security_groups:
  - sg-9a7630e2


tags:
  - {name: ipCode, value: P196}
  - {name: teamDL, value: universal.publishing.platform@ft.com}
  - {name: stopSchedule, value: nostop}

coreos_release_channel: beta
