kind: PersistentVolume
apiVersion: v1
metadata:
  name: transformers-cache-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-6330fcaa.efs.eu-west-1.amazonaws.com
    path: "/"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: transformers-cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
