apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
type: Opaque
data:
  aws.access_key_id: {{aws.access_key_id}}
  aws.secret_access_key: {{aws.secret_access_key}}
  kon.dns_api.key: {{kon.dns_api.key}}