region: eu-west-1
kms_key_arn: arn:aws:kms:eu-west-1:070529446553:key/99f50826-0102-44d5-a9dc-cd800dd204d1
debug_key_name: upp-k8s-provisioning-debug

# Controller Instance Properties
controller_instance_type: c4.large
controller_count: 2
controller_iam_role: arn:aws:iam::070529446553:instance-profile/k8s-iam-instance-profile-roles-controller-role

# ETCD Instance Properties
etcd_instance_type: t2.medium
etcd_count: 3
etcd_iam_role: arn:aws:iam::070529446553:instance-profile/k8s-iam-instance-profile-roles-etcd-role

# Worker Instance Properties
worker_pools: 
  - {instance_type: m4.xlarge, count: 2, role: worker, subnets: 3}
  - {instance_type: t2.medium, count: 3, role: mongo-worker, subnets: 3}
  - {instance_type: m4.large, count: 1, role: kafka-worker, subnets: 1}

worker_security_groups:
  - sg-9a7630e2

worker_iam_role: arn:aws:iam::070529446553:instance-profile/k8s-iam-instance-profile-roles-worker-role

vpc_id: vpc-f75fb790
vpc_cidr: 10.172.32.0/21

public_subnet_zone_a: subnet-161eea71
public_subnet_zone_b: subnet-6bb44522
public_subnet_zone_c: subnet-8f2a1ad7

private_subnet_zone_a: subnet-2a1de94d
private_subnet_zone_b: subnet-c1b94888
private_subnet_zone_c: subnet-932717cb

k8s_version: v1.7.7_coreos.0
vpc_internal_ssh_sg: sg-9a7630e2
api_private_access_sg: sg-53531d2b

nat_gw_ips:
  - 52.212.63.130
  - 52.30.225.182
  - 52.215.87.156
  - 54.194.189.228

tags:
  - {name: ipCode, value: P196}
  - {name: teamDL, value: universal.publishing.platform@ft.com}
  - {name: stopSchedule, value: nostop}
