---
- name: Provision a persistent volume for Kafka
  ec2_vol:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    zone: "{{ region }}a"
    name: "{{ stack_name }}-kafka"
    volume_size: 10
    volume_type: gp2
    tags:
      environment: "{{ environment_type }}"
      teamDL: "universal.publishing.platform@ft.com"
      systemCode: "{{ platform }}"
  register: ec2_vol_del_kafka

- name: EBS volume details
  debug:
    msg: "EBS Volume ID for delivery: '{{ ec2_vol_del_kafka.volume_id }}'"

- name: Provision a persistent volume for Mongo
  ec2_vol:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    zone: "{{ item }}"
    name: "{{ stack_name }}-mongo-{{ item }}"
    volume_size: 50
    volume_type: gp2
    tags:
      environment: "{{ environment_type }}"
      teamDL: "universal.publishing.platform@ft.com"
      systemCode: "{{ platform }}"
  with_items: 
    - "{{ region }}a"
    - "{{ region }}b"
    - "{{ region }}c"
  register: ec2_vol_del_mongo


- debug: var=ec2_vol_del_mongo

- name: Generate the S3 bucket policy for Image Publish
  template:
    src: templates/image-publish-s3.json.j2
    dest: templates/image-publish-s3.json

- name: Create an S3 bucket for Image Publish
  s3_bucket:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    name: "{{ stack_name }}-imagepublish"
    state: present
    tags:
      environment: "{{ environment_type }}"
      teamDL: "universal.publishing.platform@ft.com"
      systemCode: "{{ platform }}"

- name: Add bucket policy for the Image Publish S3 bucket
  s3_bucket:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "{{ stack_name }}-imagepublish"
    policy: "{{ lookup('file','templates/image-publish-s3.json') }}"

- name: Generate the S3 bucket policy for generic rw s3
  template:
    src: templates/generic-rw-s3.json.j2
    dest: templates/generic-rw-s3.json

- name: Create an S3 bucket for generic rw s3
  s3_bucket:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    name: "{{ stack_name }}-genericrw"
    policy: "{{ lookup('file','templates/generic-rw-s3.json') }}"
    state: present
    tags:
      environment: "{{ environment_type }}"
      teamDL: "universal.publishing.platform@ft.com"
      systemCode: "{{ platform }}"

- name: Add bucket policy for the generic rw S3 bucket
  s3_bucket:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    name: "{{ stack_name }}-genericrw"
    policy: "{{ lookup('file','templates/generic-rw-s3.json') }}"
