---
- name: Provision EBS volume for Prometheus
  ec2_vol:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ region }}"
    zone: "{{ item }}"
    name: "{{ stack_name }}-prometheus-{{ item }}"
    volume_size: 40
    volume_type: gp2
    tags:
      environment: "{{ environment_type }}"
      teamDL: "universal.publishing.platform@ft.com"
      systemCode: "{{ platform }}"
  with_items: 
    - "{{ region }}a"
    - "{{ region }}b"
  register: ec2_vol_pac_prometheus

# Volume IDs for Prometheus which needs to be added in the config
- name: EBS details for Prometheus
  set_fact:
    prometheus_volume_info: "{{ prometheus_volume_info }} + [ '{{ item.volume.zone}} => {{ item.volume_id }}' ]"
  with_items: "{{ ec2_vol_pac_prometheus.results }}"
