---
AWSTemplateFormatVersion: '2010-09-09'

Description: Stack to create S3 bucket for holding the Helm repository for upp.

Resources:

  HelmRepoBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: 'upp-helm-repo'
      WebsiteConfiguration:
        IndexDocument: "index.yaml"
      VersioningConfiguration:
        Status: "Enabled"
      Tags:
        - Key: "systemCode"
          Value: "upp"
        - Key: "environment"
          Value: "p"
        - Key: "ipCode"
          Value: "P196"
        - Key: "teamDL"
          Value: "universal.publishing.platform@ft.com"

  HelmRepoBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Ref: "HelmRepoBucket"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "HttpPublicReadOnly"
            Action: "s3:GetObject"
            Effect: "Allow"
            Resource: !Join ["", [ !GetAtt HelmRepoBucket.Arn, "/*"]]
            Principal: "*"
            Condition:
              IpAddress:
                aws:SourceIp:
                # Elastic IP address of the NAT gateway for Jenkins machines
                - 52.30.14.145
                # Park Royal
                - 213.216.148.1/32
                 # EU VPN Client
                - 62.25.64.1/32
                # US VPN Client
                - 64.210.200.1/32
                # FT Sofia Office - IP range 1
                - 94.156.217.224/29
                # FT Sofia Office - IP range 2
                - 212.36.14.64/28
                # Zetta Systems office
                - 91.92.198.46/32
                # Bracken House FTWLAN
                - 213.86.66.72/29
          - Sid: ""
            Action:
              - "s3:Put*"
              - "s3:List*"
              - "s3:Get*"
            Effect: "Allow"
            Resource:
              - !Join ["", [ !GetAtt HelmRepoBucket.Arn, "/*"]]
              - !GetAtt HelmRepoBucket.Arn
            Principal:
              AWS:
                - !Join ["", [ "arn:aws:iam::", !Ref 'AWS::AccountId', ":user/upp-helm-repo-access.prod"]]
