---
- name: Update the k8s stack
  hosts: localhost
  connection: local

  # Include the aws account specific cluster variables
  vars_files:
    - vars/defaults.yaml
    - vars/account_configs/{{ environment_type }}-{{ aws_region }}.yaml
    - vaults/{{ platform }}/vault_{{ environment_type }}.yaml

  tasks:
    - include: tasks/setup_for_kube-aws_ops.yaml

    # Check if the credentials folder is empty
    # If it is, abort the execution of the playbook
    - name: Get the number of pem files in the credentials directory
      find:
        paths: /ansible/credentials
        patterns: '*.pem'
      register: pem_files

    - name: Check if the credentials folder is empty
      fail: msg="The credentials folder is empty. Add the cluster credentials in the /ansible/credentials folder"
      when: pem_files.examined|int == 0

    - name: Validate the cluster config
      command: kube-aws validate
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"

    - name: Update the cluster
      command: kube-aws apply --force
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
