kind: ConfigMap
apiVersion: v1
metadata:
  name: load-replicator-config
  namespace: default
data:
  rates: "content:4;lists:2;enrichedcontent:2;notifications:1;brands:1;organisations:1;people:1;things:1;concordances:1;internalcontent:1"
  notfications-date: "2017-04-01T00:00:00.000Z"