kind: ConfigMap
apiVersion: v1
metadata:
  name: global-config
  namespace: default
data:
  mongodb.address: mongodb:27017
  api.host: test.api.ft.com
  aws.region: eu-west
  k8s.app_namespace: default
  aws.s3.image.binaries.bucket: com.ft.k8s-imagepublish
  aws.s3.image.binaries.url: "http://com.ft.k8s-imagepublish.s3.amazonaws.com/"
  aws.elasticsearch.endpoint: search-k8s-ltxvcgndw2flt6ygxwgq3qtdmm.eu-west-1.es.amazonaws.com
  aws.region: eu-west-1
  cache-max-age: "10"
  methode.api_uri: https://methodeapi-test.ft.com/eom-file/
  methode.health_uri: https://methodeapi-test.ft.com/build-info
  environment: "k8s-test"
  graphite.address: "graphite.ft.com:2003"
  graphite.host: graphite.ft.com
  graphite.port: "2003"
  neo4j.statements.batch.size: "50"