kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: basic-tme-transformer
  labels:
    app: basic-tme-transformer
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-tme-transformer
  template:
    metadata:
      labels:
        app: basic-tme-transformer
        visualize: "true"
    spec:
      containers:
      - name: basic-tme-transformer
        image: coco/basic-tme-transformer:1.0.0
        resources:
            limits:
              memory: 1Gi
        env:
        - name: TME_BASE
          value: "http://basic-tme-transformer:8080/transformers"
        - name: TME_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: tme.url
        - name: TME_USERNAME
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: tme.username
        - name: TME_PASSWORD
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: tme.password
        - name: TME_TOKEN
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: tme.token
        - name: CACHE_FILE_NAME
          value: "/cache/basic-tme-transformer.db"
        - name: GRAPHITE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: GRAPHITE_PREFIX
          value: coco.services.k8s.basic-tme-transformer
        - name: LOG_METRICS
          value: "false"
        - name: WRITER_ENDPOINT
          value: "http://concepts-rw-s3:8080/concepts"
        volumeMounts:
        - name: basic-tme-transformer-cache
          mountPath: /cache
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - name: basic-tme-transformer-cache
        persistentVolumeClaim:
          claimName: transformers-cache-pvc

---

kind: Service
apiVersion: v1
metadata:
  name: basic-tme-transformer
  labels:
    app: basic-tme-transformer
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: basic-tme-transformer
