kind: PersistentVolume
apiVersion: v1
metadata:
  name: composite-orgs-transformer-pv
  labels:
    failure-domain.beta.kubernetes.io/region: eu-west-1
    failure-domain.beta.kubernetes.io/zone: eu-west-1a
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0a2d380b52bcf7500
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: composite-orgs-transformer-pvc
    namespace: default

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: composite-orgs-transformer-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: composite-orgs-transformer
  labels:
    app: composite-orgs-transformer
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composite-orgs-transformer
  template:
    metadata:
      labels:
        app: composite-orgs-transformer
        visualize: "true"
    spec:
      containers:
      - name: composite-orgs-transformer
        image: coco/composite-orgs-transformer:v0.1.0
        resources:
            limits:
              memory: 4Gi
        env:
        - name: PORT
          value: "8080"
        - name: V1_TRANSFORMER_URL
          value: "http://v1-orgs-transformer:8080/transformers/organisations"
        - name: FS_TRANSFORMER_URL
          value: "https://v2-organisations-transformer-up.ft.com/transformers/organisations"
        - name: REDIRECT_BASE_URL
          value: "/__composite-orgs-transformer/transformers/organisations/"
        - name: CACHE_FILE_NAME
          value: "/cache/composite-orgs-transformer.db"
        volumeMounts:
        - name: composite-orgs-transformer-cache
          mountPath: /cache
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
      volumes:
      - name: composite-orgs-transformer-cache
        persistentVolumeClaim:
          claimName: composite-orgs-transformer-pvc

---

kind: Service
apiVersion: v1
metadata:
  name: composite-orgs-transformer
  labels:
    app: composite-orgs-transformer
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: composite-orgs-transformer
