apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: concepts-rw-s3
  labels:
    app: concepts-rw-s3
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concepts-rw-s3
  template:
    metadata:
      labels:
        app: concepts-rw-s3
        visualize: "true"
    spec:
      containers:
      - name: concepts-rw-s3
        image: coco/generic-rw-s3:1.4.0-k8s-gtg-rc.1
        resources:
            limits:
              memory: 512Mi
        env:
        - name: APP_PORT
          value: "8080"
        - name: GRAPHITE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: GRAPHITE_PREFIX
          value: "coco.services.k8s.concepts-rw-s3"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: aws.region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: aws.access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: aws.secret_access_key
        - name: BUCKET_NAME
          value: bucket_name # this bucket should be created once we have a running pub-cluster
        - name: LOG_METRICS
          value: "false"
        - name: RESOURCE_PATH
          value: "concepts"
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5

---

kind: Service
apiVersion: v1
metadata:
  name: concepts-rw-s3
  labels:
    app: concepts-rw-s3
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: concepts-rw-s3
