apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curated-authors-memberships-transformer
  labels:
    app: curated-authors-memberships-transformer
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curated-authors-memberships-transformer
  template:
    metadata:
      labels:
        app: curated-authors-memberships-transformer
        visualize: "true"
    spec:
      containers:
      - name: curated-authors-memberships-transformer
        image: coco/curated-authors-memberships-transformer:v1.0.5
        resources:
            limits:
              memory: 256Mi
        env:
        - name: PORT
          value: "8080"
        - name: BERTHA_AUTHORS_SOURCE_URL
          value: "http://bertha.ig.ft.com/view/publish/gss/1wEdVRLtayZ6-XBfYM3vKAGaOV64cNJD3L8MlLM8-uFY/TestAuthors"
        - name: BERTHA_ROLES_SOURCE_URL
          value: "http://bertha.ig.ft.com/view/publish/gss/1wEdVRLtayZ6-XBfYM3vKAGaOV64cNJD3L8MlLM8-uFY/TestRoles"
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 5

---

kind: Service
apiVersion: v1
metadata:
  name: curated-authors-memberships-transformer
  labels:
    app: curated-authors-memberships-transformer
    visualize: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: curated-authors-memberships-transformer
