kind: PersistentVolume
apiVersion: v1
metadata:
  name: factset-reader-pv
  labels:
    failure-domain.beta.kubernetes.io/region: eu-west-1
    failure-domain.beta.kubernetes.io/zone: eu-west-1b
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-084e6acdd0255db57
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: factset-reader-pvc
    namespace: default

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: factset-reader-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: factset-reader
  labels:
    app: factset-reader
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factset-reader
  template:
    metadata:
      labels:
        app: factset-reader
        visualize: "true"
    spec:
      containers:
      - name: factset-reader
        image: coco/factset-reader:0.1.0-xp-gtg-rc.2
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi
        volumeMounts:
        - name: factset-persistent
          mountPath: /data
          subPath: factset-data
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: aws.access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: aws.secret_access_key
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: aws.s3.factset.bucket
        - name: S3_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: aws.s3.domain
        - name: FACTSET_USER
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: factset.user
        - name: FACTSET_KEY
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: factset.key
        - name: FACTSET_FTP
          value: fts-sftp.factset.com
        - name: FACTSET_RESOURCES
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: factset.resources
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 2
      volumes:
      - name: factset-persistent
        persistentVolumeClaim:
          claimName: factset-reader-pvc

---

kind: Service
apiVersion: v1
metadata:
  name: factset-reader
  labels:
    app: factset-reader
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: factset-reader
