apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: publish-availability-monitor
  labels:
    app: publish-availability-monitor
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publish-availability-monitor
  template:
    metadata:
      labels:
        app: publish-availability-monitor
        version: "latest"
        visualize: "true"
    spec:
      containers:
      - name: publish-availability-monitor
        image: coco/publish-availability-monitor:v0.24.17-k8s-version-rc12
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
        env:
        - name: KAFKA_TOPIC
          value: "PreNativeCmsPublicationEvents"
        - name: KAFKA_PROXY_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: kafka.proxy.url
        - name: QUEUE_ADDR
          value: "http://kafka:8082"
        - name: CONTENT_URL
          value: "/__document-store-api/content/"
        - name: INTERNAL_COMPONENTS_URL
          value: "/__document-store-api/internalcomponents/"
        - name: LISTS_URL
          value: "/__document-store-api/lists/"
        - name: NOTIFICATIONS_URL
          value: "/__notifications-rw/content/notifications?type=all"
        - name: NOTIFICATIONS_PUSH_URL
          value: "/content/notifications-push?monitor=true"
        - name: LISTS_NOTIFICATIONS_URL
          value: "/__list-notifications-rw/lists/notifications"
        - name: LISTS_NOTIFICATIONS_PUSH_URL
          value: "/lists/notifications-push?monitor=true"
        - name: METHODE_ARTICLE_VALIDATION_URL
          value: "https://k8s-delivery-upp-eu.ft.com/__methode-article-mapper/map"
        - name: METHODE_CONTENT_PLACEHOLDER_MAPPER_URL
          value: "https://k8s-delivery-upp-eu.ft.com/__methode-content-placeholder-mapper/map"
        - name: METHODE_IMAGE_MODEL_MAPPER_URL
          value: "https://k8s-delivery-upp-eu.ft.com/__methode-image-model-mapper/map"
        - name: METHODE_LIST_VALIDATION_URL
          value: "https://k8s-delivery-upp-eu.ft.com/__methode-list-mapper/map"
        - name: METHODE_ARTICLE_INTERNAL_COMPONENTS_MAPPER_URL
          value: "https://k8s-delivery-upp-eu.ft.com/__methode-article-internal-components-mapper/map"
        - name: VIDEO_MAPPER_URL
          value: "https://k8s-delivery-upp-eu.ft.com/__video-mapper/map"
        - name: WORDPRESS_MAPPER_URL
          value: "https://k8s-delivery-upp-eu.ft.com/__wordpress-article-mapper/map"
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        volumeMounts:
        - name: read-envs-config
          mountPath: /etc/pam/envs
        - name: pam-secrets
          mountPath: /etc/pam/credentials
      volumes:
      - name: pam-secrets
        secret:
          secretName: publish-availability-monitor-secrets
          items:
          - key: read-credentials
            path: read-environments-credentials.json
          - key: validator-credentials
            path: validator-credentials.json
      - name: read-envs-config
        configMap:
          name: monitoring-configs
          items:
          - key: environments
            path: read-environments.json

---

kind: Service
apiVersion: v1
metadata:
  name: publish-availability-monitor
  labels:
    app: publish-availability-monitor
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: publish-availability-monitor
