apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: subjects-transformer
  labels:
    app: subjects-transformer
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subjects-transformer
  template:
    metadata:
      labels:
        app: subjects-transformer
        visualize: "true"
    spec:
      containers:
      - name: subjects-transformer
        image: coco/subjects-transformer:v1.0.7
        resources:
            limits:
              memory: 256Mi
        env:
        - name: PORT
          value: "8080"
        - name: BASE_URL
          value: "http://subjects-transformer:8080/transformers/subjects/"
        - name: TME_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: tme.url
        - name: TME_USERNAME
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: tme.username
        - name: TME_PASSWORD
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: tme.password
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: tme.token
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 5

---

kind: Service
apiVersion: v1
metadata:
  name: subjects-transformer
  labels:
    app: subjects-transformer
    visualize: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: subjects-transformer
