kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: v1-orgs-transformer
  labels:
    app: v1-orgs-transformer
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v1-orgs-transformer
  template:
    metadata:
      labels:
        app: v1-orgs-transformer
        visualize: "true"
    spec:
      containers:
      - name: v1-orgs-transformer
        image: coco/v1-orgs-transformer:v1.2.0
        resources:
            limits:
              memory: 1536Mi
        env:
        - name: PORT
          value: "8080"
        - name: BASE_URL
          value: "http://v1-orgs-transformer:8080/transformers/organisations/"
        - name: TME_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: tme.url
        - name: TME_USERNAME
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: tme.username
        - name: TME_PASSWORD
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: tme.password
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: tme.token
        - name: CACHE_FILE_NAME
          value: "/cache/v1-orgs-transformer.db"
        - name: GRAPHITE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: GRAPHITE_PREFIX
          value: "coco.services.k8s.v1-orgs-transformer"
        - name: LOG_METRICS
          value: "false"
        volumeMounts:
        - name: v1-orgs-transformer-cache
          mountPath: /cache
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
      volumes:
      - name: v1-orgs-transformer-cache
        persistentVolumeClaim:
          claimName: transformers-cache-pvc

---

kind: Service
apiVersion: v1
metadata:
  name: v1-orgs-transformer
  labels:
    app: v1-orgs-transformer
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: v1-orgs-transformer
