kind: PersistentVolume
apiVersion: v1
metadata:
  name: v1-people-transformer-pv
  labels:
    failure-domain.beta.kubernetes.io/region: eu-west-1
    failure-domain.beta.kubernetes.io/zone: eu-west-1c
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-05131bec4521a78ce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: v1-people-transformer-pvc
    namespace: default

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: v1-people-transformer-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: v1-people-transformer
  labels:
    app: v1-people-transformer
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v1-people-transformer
  template:
    metadata:
      labels:
        app: v1-people-transformer
        visualize: "true"
    spec:
      containers:
      - name: v1-people-transformer
        image: coco/v1-people-transformer:v0.1.0
        resources:
            limits:
              memory: 1Gi
        env:
        - name: PORT
          value: "8080"
        - name: BASE_URL
          value: "http://v1-people-transformer:8080/transformers/people/"
        - name: TME_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: tme.url
        - name: TME_USERNAME
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: tme.username
        - name: TME_PASSWORD
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: tme.password
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: tme.token
        - name: CACHE_FILE_NAME
          value: "/cache/v1-people-transformer.db"
        - name: GRAPHITE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: GRAPHITE_PREFIX
          value: "coco.services.k8s.v1-people-transformer"
        - name: LOG_METRICS
          value: "false"
        volumeMounts:
        - name: v1-people-transformer-cache
          mountPath: /cache
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 5
      volumes:
      - name: v1-people-transformer-cache
        persistentVolumeClaim:
          claimName: v1-people-transformer-pvc

---

kind: Service
apiVersion: v1
metadata:
  name: v1-people-transformer
  labels:
    app: v1-people-transformer
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: v1-people-transformer
