apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-notifier
  labels:
    app: wordpress-notifier
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-notifier
  template:
    metadata:
      labels:
        app: wordpress-notifier
        visualize: "true"
    spec:
      containers:
      - name: wordpress-notifier
        image: up-registry.ft.com/coco/k8s-wordpress-notifier:v2
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: "-Xms544m -Xmx544m -XX:+UseG1GC -server"
        - name: WORDPRESS_CONTENTAPI_KEY
          valueFrom:
            secretKeyRef:
              name: global-secrets
              key: wordpress.content.api.key
        - name: CMS_NOTIFIER_URL
          value: cms-notifier:8080
        ports:
        - containerPort: 8080
        - containerPort: 8081
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /__gtg
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: wordpress-notifier
  labels:
    app: wordpress-notifier
    visualize: "true"
    hasHealthcheck: "true"
spec:
  ports:
    - port: 8080
      name: "app"
      targetPort: 8080
    - port: 8081
      name: "admin"
      targetPort: 8081
  selector:
    app: wordpress-notifier
